name: Beta Compile

on:
  pull_request:

jobs:
  build:
    name: Compile
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DISPATCH_REPO }}
          repository: chiefmikey/gitlang

      - name: Merge Branches
        env:
          GH_TOKEN: ${{ secrets.DISPATCH_REPO }}
        run: |
          git config user.name "chiefmikey"
          git config user.email "wolfemikl@gmail.com"
          git remote add upstream https://github.com/chiefmikey/gitlang-beta.git
          echo test: $(gh pr list -R chiefmikey/gitlang-beta -s open --json headRefName | jq -r '.[] | .headRefName')
          for branch in $(gh pr list -s open --json headRefName | jq -r '.[] | .headRefName'); do
            # git fetch upstream ${branch}
            git merge --allow-unrelated-histories upstream/${branch} || true
          done

      - name: Push to Main
        run: |
          git push -fu upstream main
